name: Build OrangeFox from modern Ubuntu repositories. Instead:
- Replace it with `python2.7` if absolutely required.
- Recovery

on:
  push:
    branches: [ main ]
 Otherwise, migrate to `python3`, which is actively maintained and widely used.

### Updated Workflow File
  pull_request:
    branches: [ main ]
  workflow_dispatch:Replace the `apt-get install` command in the `Set up    # <-- Enables manual trigger from the Actions tab build environment` step in the workflow file with the following

jobs:
  build:
    runs-on: ubuntu-20.04:

```yaml
      - name: Set up build environment
        run: |
          sudo apt-get update  # Use an older version of Ubuntu for compatibility

    steps
          sudo apt-get install -y git bc bison build-essential curl flex g++-multilib gcc-multilib:
      - name: Checkout code
        uses: actions/checkout \
            gnupg gperf imagemagick lib32ncurses@v4

      - name: Set up build environment
5-dev lib32readline-dev lib32z1-dev \
            liblz4        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison build-essential curl flex-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 g++-multilib gcc-multilib \
            gnup libxml2-utils \
            lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-devg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev \
            liblz4-tool libncurses \
            libwxgtk3.2-dev python3
