name: Build OrangeFox Recovery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # <-- This enables manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison build-essential curl flex g++-multilib gcc-multilib \
            gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev \
            liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
            lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
            libwxgtk3.0-gtk3-dev python2 python3

      - name: Build OrangeFox Recovery
        run: |
          # Replace this with your real build commands
          chmod +x build.sh
          ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: orangefox-build
          path: out/*.img
